"""empty message

Revision ID: 0d51cc2e02ec
Revises: e8cd2723d161
Create Date: 2024-03-23 14:26:21.789895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d51cc2e02ec'
down_revision = 'e8cd2723d161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('task_category', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('task_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
